LOCAL_PATH := $(call my-dir)
# Override Framework Compatibility Matrix
# The compatibility_matrix.xml is copied from $OUT/system/compatibility_matrix.xml,
# which is generated by build system. We modify the its kernel defconfig to stay the
# same with maruos modification of kernel defconfig.
# So we should upgrade it when system updating.
include $(CLEAR_VARS)
LOCAL_MODULE := override_system_compatibility_matrix.xml
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_STEM := compatibility_matrix.xml
LOCAL_MODULE_PATH := $(TARGET_OUT)
LOCAL_OVERRIDES_PACKAGES := system_compatibility_matrix.xml
LOCAL_PREBUILT_MODULE_FILE := $(LOCAL_PATH)/compatibility_matrix.xml
include $(BUILD_PREBUILT)